Repository arviz-devs/arviz, pull requests merged in 2021-01, with the labels that each got.

#1484 Add always-visible titles to the example gallery.
  CHANGELOG.md
  arviz/plots/khatplot.py
  arviz/plots/separationplot.py
  doc/sphinxext/gallery_generator.py
  examples/bokeh/bokeh_plot_loo_pit_ecdf.py
  examples/bokeh/bokeh_plot_loo_pit_overlay.py
  examples/matplotlib/mpl_plot_autocorr.py
  examples/matplotlib/mpl_plot_compare.py
  examples/matplotlib/mpl_plot_density.py
  examples/matplotlib/mpl_plot_dist.py
  examples/matplotlib/mpl_plot_energy.py
  examples/matplotlib/mpl_plot_ess_evolution.py
  examples/matplotlib/mpl_plot_ess_local.py
  examples/matplotlib/mpl_plot_ess_quantile.py
  examples/matplotlib/mpl_plot_forest.py
  examples/matplotlib/mpl_plot_forest_ridge.py
  examples/matplotlib/mpl_plot_joint.py
  examples/matplotlib/mpl_plot_kde.py
  examples/matplotlib/mpl_plot_kde_2d.py
  examples/matplotlib/mpl_plot_kde_quantiles.py
  examples/matplotlib/mpl_plot_khat.py
  examples/matplotlib/mpl_plot_loo_pit_ecdf.py
  examples/matplotlib/mpl_plot_loo_pit_overlay.py
  examples/matplotlib/mpl_plot_mcse.py
  examples/matplotlib/mpl_plot_mcse_errorbar.py
  examples/matplotlib/mpl_plot_pair.py
  examples/matplotlib/mpl_plot_pair_hex.py
  examples/matplotlib/mpl_plot_pair_kde.py
  examples/matplotlib/mpl_plot_pair_point_estimate.py
  examples/matplotlib/mpl_plot_parallel.py
  examples/matplotlib/mpl_plot_parallel_minmax.py
  examples/matplotlib/mpl_plot_parallel_normal.py
  examples/matplotlib/mpl_plot_posterior.py
  examples/matplotlib/mpl_plot_ppc.py
  examples/matplotlib/mpl_plot_ppc_cumulative.py
  examples/matplotlib/mpl_plot_rank.py
  examples/matplotlib/mpl_plot_separation.py
  examples/matplotlib/mpl_plot_trace.py
  examples/matplotlib/mpl_plot_trace_bars.py
  examples/matplotlib/mpl_plot_trace_vlines.py
  examples/matplotlib/mpl_plot_violin.py
  examples/matplotlib/mpl_styles.py
Labels: User Documentation

#1501 Add copy() method to InferenceData
  CHANGELOG.md
  arviz/data/inference_data.py
Labels: Enhancement

#1527 Removed repetitive variable names from forest plots of multivariate variables
  CHANGELOG.md
  arviz/plots/backends/bokeh/forestplot.py
  arviz/plots/backends/matplotlib/forestplot.py
Labels: Enhancement, Feature Request
